### ISSUE TITLE
[Bug]: Unable to generate playbooks and endpoints

### ISSUE THREAD

**Issue by zafar0506** [apisec-inc/Support#62]
### Severity

Blocker

### What happened?

Unable to generate playbooks & endpoints for a spec file (Landmark tenant).
Please find the attached spec file for reference.
[panel-conveyancing-transaction-request-service.zip](https://github.com/apisec-inc/Support/files/8440409/panel-conveyancing-transaction-request-service.zip)

**Comment by Abdullah-Akbar** [comment]
The spec seems invalid.  We can inspect errors using https://editor.swagger.io/

**Comment by syedimranapisecai** [comment]
The spec is in yaml format

**Comment by zafar0506** [comment]
Please find rectified spec file. I have also tested it on swagger editor but no issues were found.
I assume that the platform should inform the user about invalid specs.
[panel-conveyancing-transaction-request-service.zip](https://github.com/apisec-inc/Support/files/8440724/panel-conveyancing-transaction-request-service.zip)

**Comment by Mohammed-Luqman-Shareef** [comment]
There is a prob in the spec file.  At lines 568, 569, 570, 571 there is no space after :
see the SS below.
You need to add one space after : 
![image](https://user-images.githubusercontent.com/87166065/162148782-e085a722-6d65-4cd8-96b1-d62ee452b324.png)

But right now it seems the register with file upload is not working.  For you you can fix the spec and upload it to some publica location like github repo or dropbox and use that url to register it.

**Comment by syedimranapisecai** [comment]
Control-plane exception logs for project registered with this specs.

```
2022-04-07 07:55:34.932  INFO 1 --- [        rating2] c.f.f.s.p.send.GaaSTaskRequestProcessor  : Payload size [0] for project [8a7483438002e2f50180030583d45253]
2022-04-07 07:55:34.935  WARN 1 --- [        rating2] c.f.f.s.p.send.GaaSTaskRequestProcessor  : Unable to process AutoConfig for new project

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:141) ~[na:na]
	at com.fxlabs.fxt.services.processors.send.GaaSTaskRequestProcessor.processNewProjectAutoCodeconfig(GaaSTaskRequestProcessor.java:403) ~[Services-0.0.1-SNAPSHOT.jar!/:na]
	at com.fxlabs.fxt.services.processors.send.GaaSTaskRequestProcessor$$FastClassBySpringCGLIB$$5c502a68.invoke(<generated>) ~[Services-0.0.1-SNAPSHOT.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76) ~[javamelody-core-1.77.0.jar!/:1.77.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]



```

**Comment by Mohammed-Luqman-Shareef** [comment]
Engineering is looking into this issue.

The work around for now is to upload the spec somewhere and use its url to register it.

**Comment by zafar0506** [comment]
@Mohammed-Luqman-Shareef :  will try to upload it to a public repo and then register it.
@muqeetkhan20 :  tried with the converted JSON format,  still for me playbooks are not generated.

**Comment by zafar0506** [comment]
@Abdullah-Akbar  : As discussed and demonstrated, Please find attached specs for further investigation. Registration is working but playbook generation is not working. No proper messaging is available.
[panel-conveyancing-transaction-request-service.zip](https://github.com/apisec-inc/Support/files/8441435/panel-conveyancing-transaction-request-service.zip)

**Comment by Mohammed-Luqman-Shareef** [comment]
@zafar0506 ,   The Spec for "panel-conveyancing...." has some issues in it.  There are some invalid references.  
For Example at line 394
 "$ref": "../../apihub--apihub--published-lgs/1.2.0/lgsAddress.json#/components/schemas/lgsAddressFixedLine"  
It refers to some json which doesnt exist.  If you remove all such references it will work,

**Comment by intesar** [comment]
@zafar0506 if the issue is fixed. Please close the ticket.

**Comment by zafar0506** [comment]
With application refresh, the issue seems to be fixed. Hence closing the issue.
